---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: dns
spec:
  acme:
    email: matte.hemmingsson@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: acme-dns-key
    solvers:
      - dns01:
          acmeDNS:
            host: https://auth.acme-dns.io
            accountSecretRef:
              name: acme-dns-accounts
              key: acme-dns-accounts.json
