
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frigate
  namespace: argocd
spec:
  project: core
  source:
    chart: frigate
    repoURL: https://blakeblackshear.github.io/blakeshome-charts/
    targetRevision: 7.5.1
    helm:
      releaseName: frigate
      values: |
        coral:
          enabled: false
        env:
          FRIGATE_RTSP_PASSWORD: "rtsgtff"
        persistence:
          media:
            enabled: true
            size: 1000Gi
        config: |
          mqtt:
            host: "mqtt.example.com"
            port: 1883
            user: admin
            password: "<your_mqtt_password>"
          cameras:
            # Define at least one camera
            doorbell:
              ffmpeg:
                inputs:
                  - path: rtsp://admin:Vete22@192.168.1.114:554/h264Preview_01_main 
                    roles:
                      - detect
                      - clips
                      - record


  destination:
    server: "https://kubernetes.default.svc"
    namespace: traefik
  syncPolicy:
    syncOptions:
      - CreateNamespace=true

