apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homeassistant
  namespace: home
  annotations:
    volume.beta.kubernetes.io/storage-class: "truenas-iscsi-nonroot"
spec:
  storageClassName: truenas-iscsi-nonroot
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: homeassistant
  namespace: home
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homeassistant
  template:
    metadata:
      labels:
        app: homeassistant
      containers:
      - name: homeassistant
        image: homeassistant/home-assistant
        imagePullPolicy: Always
        volumeMounts:
        - name: homeassistant
          mountPath: /config
        - name: localtime
          mountPath: /etc/localtime
        - name: dev-zwave
          mountPath: /dev/usbzwave
        - name: dev-insteon
          mountPath: /dev/usbinsteon
        securityContext:
          privileged: true
      - name: appdaemon
        image: mezz64/appdaemon
        imagePullPolicy: Always
        volumeMounts:
        - name: appdaemon
          mountPath: /conf
        - name: localtime
          mountPath: /etc/localtime
      volumes:
      - name: homeassistant
        persistentVolumeClaim:
          claimName: homeassistant
      #- name: hadashboard
      #  persistentVolumeClaim:
      #    claimName: hadashboard
      #- name: hapush
      #  persistentVolumeClaim:
      #    claimName: hapush
      - name: localtime
        hostPath:
          path: /etc/localtime
      #- name: dev-zwave
      #  hostPath:
      #    path: /dev/usbzwave
      #- name: dev-insteon
      #  hostPath:
      #    path: /dev/usbinsteon
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: homeassistant
  name: homeassistant
  namespace: home
spec:
  ports:
  - name: homeassistant
    port: 8123
    protocol: TCP
    targetPort: 8123
  selector:
    app: homeassistant
  sessionAffinity: None
  type: ClusterIP