apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homeassistant
  namespace: home
  annotations:
    volume.beta.kubernetes.io/storage-class: "truenas-iscsi-nonroot"
spec:
  storageClassName: truenas-iscsi-nonroot
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: homeassistant
  namespace: home
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homeassistant
  template:
    metadata:
      labels:
        app: homeassistant
    spec:
      containers:
        - name: homeassistant
          # https://hub.docker.com/r/pihole/pihole/tags
          image: homeassistant/home-assistant
          imagePullPolicy: IfNotPresent
          env:
            - name: TZ
              value: "America/Los_Angeles"
            - name: WEBPASSWORD
              value: "v2password"
          #securityContext:
          #  privileged: true
          ports:
            - containerPort: 8123
              protocol: TCP
          volumeMounts:
             - name: homeassistant
               mountPath: /config
          resources:
            requests:
              memory: 128Mi
              cpu: 100m
            limits:
              memory: 2Gi
              cpu: 1000m
      volumes:
        - name: homeassistant
          persistentVolumeClaim:
            claimName: homeassistant
        #- name: dev-zwave
        #  hostPath:
        #    path: /dev/usbzwave
        #- name: dev-insteon
        #  hostPath:
        #    path: /dev/usbinsteon


---  
apiVersion: v1
kind: Service
metadata:
  labels:
    app: homeassistant
  name: homeassistant
  namespace: home
spec:
  ports:
  - name: homeassistant
    port: 8123
    protocol: TCP
    targetPort: 8123
  selector:
    app: homeassistant
  sessionAffinity: None
  type: ClusterIP