apiVersion: v1
kind: ConfigMap
metadata:
  name: mktxp
  namespace: home
data:
  mktxp.conf: |
    [main-fw]
        # for specific configuration on the router level, overload the defaults here
        hostname = 192.168.1.1

    [hus-sw1]
        # for specific configuration on the router level, overload the defaults here
        hostname = 192.168.1.5

    [default]
        # this affects configuration of all routers, unless overloaded on their specific levels

        enabled = True          # turns metrics collection for this RouterOS device on / off
        hostname = localhost    # RouterOS IP address
        port = 8728             # RouterOS IP Port

        username = prometheus     # RouterOS user, needs to have 'read' and 'api' permissions
        password = password

        use_ssl = False                 # enables connection via API-SSL servis
        no_ssl_certificate = False      # enables API_SSL connect without router SSL certificate
        ssl_certificate_verify = False  # turns SSL certificate verification on / off   
        plaintext_login = True          # for legacy RouterOS versions below 6.43 use False

        installed_packages = True       # Installed packages
        dhcp = True                     # DHCP general metrics
        dhcp_lease = True               # DHCP lease metrics

        connections = True              # IP connections metrics
        connection_stats = False        # Open IP connections metrics 

        interface = True                # Interfaces traffic metrics

        route = True                    # IPv4 Routes metrics
        pool = True                     # IPv4 Pool metrics
        firewall = True                 # IPv4 Firewall rules traffic metrics
        neighbor = True                 # IPv4 Reachable Neighbors

        ipv6_route = False              # IPv6 Routes metrics    
        ipv6_pool = False               # IPv6 Pool metrics
        ipv6_firewall = False           # IPv6 Firewall rules traffic metrics
        ipv6_neighbor = False           # IPv6 Reachable Neighbors

        poe = True                      # POE metrics
        monitor = True                  # Interface monitor metrics
        netwatch = True                 # Netwatch metrics
        public_ip = True                # Public IP metrics
        wireless = True                 # WLAN general metrics
        wireless_clients = True         # WLAN clients metrics
        capsman = True                  # CAPsMAN general metrics
        capsman_clients = True          # CAPsMAN clients metrics

        lte = False                     # LTE signal and status metrics (requires additional 'test' permission policy on RouterOS v6) 
        ipsec = False                   # IPSec active peer metrics
        switch_port = False             # Switch Port metrics

        kid_control_assigned = False    # Allow Kid Control metrics for connected devices with assigned users
        kid_control_dynamic = False     # Allow Kid Control metrics for all connected devices, including those without assigned user

        user = True                     # Active Users metrics
        queue = True                    # Queues metrics

        bgp = False                     # BGP sessions metrics

        remote_dhcp_entry = None        # An MKTXP entry to provide for remote DHCP info / resolution
        remote_capsman_entry = None     # An MKTXP entry to provide for remote capsman info 

        use_comments_over_names = True  # when available, forces using comments over the interfaces names
        check_for_updates = False       # check for available ROS updates

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mikrotik-exporter
  namespace: home
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mikrotik-exporter
  template:
    metadata:
      labels:
        app: mikrotik-exporter
    spec:
      containers:
      - name: mikrotik-exporter
        image: ghcr.io/akpw/mktxp:latest
        ports:
        - containerPort: 49090 
        volumeMounts:
        - name: config
          mountPath: /home/mktxp/mktxp/
      volumes:
        - name: config
          projected:
            sources:
              - configMap:
                  name: mktxp

---
apiVersion: v1
kind: Service
metadata:
  name: mikrotik-exporter
  namespace: home
spec:
  type: ClusterIP
  selector:
    app: mikrotik-exporter  
  ports:
  - port: 49090
