---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: samma-stack-elasticsearch
  namespace: elastic
  labels:
    sammastack: elasticsearch
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.init: regex:^3.10.*
    fluxcd.io/tag.podinfod: semver:~3.1
spec:
  replicas: 1
  selector:
    matchLabels:
      sammastack: elasticsearch
  template:
    metadata:
      labels:
        sammastack: elasticsearch
    spec:
      containers:
      - name: elasticsearch
        image: "docker.elastic.co/elasticsearch/elasticsearch:8.0.0-SNAPSHOT"
        imagePullPolicy: Always
        env:
        - name: discovery.type
          value: single-node
        - name: ES_JAVA_OPTS
          value: -Xms512m -Xmx512m
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1G"
            cpu: "500m"
        ports:
        - name: http
          containerPort: 9200
          protocol: TCP
        livenessProbe:
        readinessProbe:
          httpGet:
            path: /_cluster/health
            port: http
        volumeMounts:
        - mountPath: /usr/share/elasticsearch/data
          name: data
      volumes:
      - name: data
        nfs:
          server: 10.100.0.5
          path: /opt/kubernetes/elasticsearch
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: elastic
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.init: regex:^3.10.*
    fluxcd.io/tag.podinfod: semver:~3.1
spec:
  selector:
    sammastack: elasticsearch
  ports:
  - protocol: TCP
    port: 9200
    targetPort: 9200
