#!/usr/bin/env bash
# Regenerate both ConfigMaps:
#   configmap-server.yaml  <- skills_mcp.py       (the server source lives here)
#   configmap-skills.yaml  <- the agent-skills registry
#
# The MCP server serves whatever is in this ConfigMap. The registry itself is a
# separate private repo (github.com/mattiashem/agent-skills), so this file is a
# SNAPSHOT of it — rerun this script and commit after every skill change.
#
# Swapping to live sync later is a small change: drop a git-sync sidecar with a
# read-only token into deployment.yaml, point it at /skills, and delete this
# ConfigMap along with the volume that mounts it.
#
# Usage:  ./generate-skills-configmap.sh [path-to-agent-skills-repo]

set -euo pipefail

REPO="${1:-$HOME/projects/agent-skills}"
SKILLS_DIR="$REPO/skills"
HERE="$(dirname "$0")"
OUT="$HERE/configmap-skills.yaml"

[ -d "$SKILLS_DIR" ] || { echo "no skills dir at $SKILLS_DIR" >&2; exit 1; }

# --- server ConfigMap, from the .py source in this directory ---------------
python3 - "$HERE/skills_mcp.py" "$HERE/configmap-server.yaml" <<'PY'
import pathlib, sys

src, out = pathlib.Path(sys.argv[1]), pathlib.Path(sys.argv[2])
body = "\n".join("    " + l if l.strip() else "" for l in src.read_text().split("\n"))
out.write_text(
    "# GENERATED by generate-configmaps.sh from skills_mcp.py - do not edit by hand.\n"
    "apiVersion: v1\n"
    "kind: ConfigMap\n"
    "metadata:\n"
    "  name: skills-mcp-server\n"
    "  namespace: skills\n"
    "data:\n"
    "  skills_mcp.py: |\n" + body + "\n"
)
print(f"wrote {out} from {src.name}")
PY

python3 - "$SKILLS_DIR" "$OUT" <<'PY'
import pathlib, sys

skills_dir, out = pathlib.Path(sys.argv[1]), pathlib.Path(sys.argv[2])
parts = [
    "# GENERATED by generate-skills-configmap.sh — do not edit by hand.",
    "# Source of truth: github.com/mattiashem/agent-skills",
    "apiVersion: v1",
    "kind: ConfigMap",
    "metadata:",
    "  name: skills-mcp-content",
    "  namespace: skills",
    "data:",
]

total = 0
for d in sorted(p for p in skills_dir.iterdir() if p.is_dir()):
    f = d / "SKILL.md"
    if not f.is_file():
        continue
    text = f.read_text(encoding="utf-8")
    total += len(text.encode())
    # ConfigMap keys cannot contain "/", so the slug is encoded in the key and
    # split back into <slug>/SKILL.md by the initContainer.
    parts.append(f"  {d.name}__SKILL.md: |")
    parts += ["    " + line if line.strip() else "" for line in text.split("\n")]

out.write_text("\n".join(parts) + "\n")
print(f"wrote {out} — {len(parts)} lines, {total} bytes of skill content")
if total > 900_000:
    print("WARNING: approaching the 1 MiB ConfigMap limit", file=sys.stderr)

# Stamp the content hash onto the Deployment so a skill change actually rolls
# the pod, instead of waiting on kubelet's ConfigMap sync period.
import hashlib, re

# Hash BOTH ConfigMaps: a server code change must roll the pod just as a skill
# change does, since neither is picked up by a running process on its own.
h = hashlib.sha256()
for f in ("configmap-server.yaml", "configmap-skills.yaml"):
    h.update((out.parent / f).read_bytes())
digest = h.hexdigest()[:16]
dep = out.parent / "deployment.yaml"
if dep.is_file():
    text = dep.read_text()
    patched = re.sub(r'(checksum/skills: ").*(")', r'\g<1>' + digest + r'\g<2>', text, count=1)
    if patched != text:
        dep.write_text(patched)
        print(f"stamped checksum/skills={digest} onto deployment.yaml")
PY
