apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: home
  namespace: argocd
spec:
  project: core
  source:
    repoURL: git@github.com:mattiashem/v2-k8s.git
    targetRevision: HEAD
    path: home
  destination:
    server: https://kubernetes.default.svc