apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
spec:
  project: core
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: git@github.com:mattiashem/v2-k8s.git
    targetRevision: HEAD
    path: keycloak
  destination:
    server: "https://kubernetes.default.svc"
    namespace: code
