apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
  labels:
    type: network
    when: init
    cat: core
    owner: plattform
spec:
  project: plattform
  source:
    chart: metallb
    repoURL: https://metallb.github.io/metallb
    targetRevision: 0.13.10
    helm:
      releaseName: metallb
  destination:
    server: "https://kubernetes.default.svc"
    namespace: metallb-system
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
  ignoreDifferences:
    - group: "apiextensions.k8s.io"
      kind: CustomResourceDefinition
      name: bgppeers.metallb.io
      jsonPointers:
      - /spec/conversion/webhook/clientConfig/caBundle
    - group: "apiextensions.k8s.io"
      kind: CustomResourceDefinition
      name: addresspools.metallb.io
      jsonPointers:
      - /spec/conversion/webhook/clientConfig/caBundle
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: lan
  namespace: metallb-system
spec:
  addresses:
  - 10.0.0.100/32
  - 10.0.0.101/32
  - 10.0.0.102/32
  - 10.0.0.103/32
  - 10.0.0.104/32
  - 10.0.0.105/32
  - 10.0.0.106/32
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: ip
  namespace: metallb-system
spec:
  ipAddressPools:
  - lan

