apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
spec:
  project: core
  source:
    chart: metallb
    repoURL: https://metallb.github.io/metallb
    targetRevision: 0.13.10
    helm:
      releaseName: metallb
  destination:
    server: "https://kubernetes.default.svc"
    namespace: metallb-system
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
  ignoreDifferences:
    - group: "apiextensions.k8s.io"
      kind: CustomResourceDefinition
      name: bgppeers.metallb.io
      jsonPointers:
      - /spec/conversion/webhook/clientConfig/caBundle
    - group: "apiextensions.k8s.io"
      kind: CustomResourceDefinition
      name: addresspools.metallb.io
      jsonPointers:
      - /spec/conversion/webhook/clientConfig/caBundle
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: dmz
  namespace: metallb-system
spec:
  autoAssign: false
  addresses:
  - 10.0.0.100/32
  - 10.0.0.101/32
  - 10.0.0.102/32
  - 10.0.0.103/32
  - 10.0.0.104/32
  - 10.0.0.105/32
  - 10.0.0.106/32
---

apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: lan
  namespace: metallb-system
spec:
  autoAssign: false
  addresses:
  - 192.168.1.14/32
  - 192.168.1.15/32
  - 192.168.1.40/32
  - 192.168.1.41/32
  - 192.168.1.42/32
  - 192.168.1.43/32
  - 192.168.1.44/32
  - 192.168.1.45/32
---

apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: pihole
  namespace: metallb-system
spec:
  autoAssign: false
  addresses:
  - 10.0.0.107/32
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: pihole-lan
  namespace: metallb-system
spec:
  autoAssign: false
  addresses:
  - 192.168.1.12/32
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: pihole-lan2
  namespace: metallb-system
spec:
  autoAssign: false
  addresses:
  - 192.168.1.13/32
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: ip
  namespace: metallb-system
spec:
  ipAddressPools:
  - lan
  - dmz
  - pihole
  - pihole-lan
  - pihole-lan2

