apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  project: core
  source:
    chart: prometheus
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 23.3.0
    helm:
      releaseName: prometheus
      values: |
        alertmanager:
          enabled: false
        server:
          persistentVolume:
            size: 200Gi
          statefulSet:
            ## If true, use a statefulset instead of a deployment for pod management.
            ## This allows to scale replicas to more than 1 pod
            ##
            enabled: true
          extraFlags:
            - storage.tsdb.retention.size=150GB
          resources: 
            limits:
              cpu: 2000m
              memory: 4Gi
            requests:
              cpu: 500m
              memory: 512Mi
          ## Prometheus data retention period (default if not specified is 15 days)
          ##
          retention: ""
          ## Prometheus' data retention size. Supported units: B, KB, MB, GB, TB, PB, EB.
          ##
          retentionSize: "150GB"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: metrics
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: node-exporter
  namespace: argocd
spec:
  project: core
  source:
    chart: prometheus-node-exporter
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 4.39.0
    helm:
      releaseName: prometheus-node-exporter
      values: |
        alertmanager:
          enabled: false
        server:
          persistentVolume:
            size: 200Gi
          statefulSet:
            ## If true, use a statefulset instead of a deployment for pod management.
            ## This allows to scale replicas to more than 1 pod
            ##
            enabled: true
          extraFlags:
            - storage.tsdb.retention.size=150GB
          resources: 
            limits:
              cpu: 2000m
              memory: 4Gi
            requests:
              cpu: 500m
              memory: 512Mi
          ## Prometheus data retention period (default if not specified is 15 days)
          ##
          retention: ""
          ## Prometheus' data retention size. Supported units: B, KB, MB, GB, TB, PB, EB.
          ##
          retentionSize: "150GB"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: metrics
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-state
  namespace: argocd
spec:
  project: core
  source:
    chart: kube-state-metrics
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 5.10.1
    helm:
      releaseName: kube-state-metrics
  destination:
    server: "https://kubernetes.default.svc"
    namespace: metrics
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
---
#https://github.com/grafana/helm-charts/blob/main/charts/grafana/README.md
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: core
  source:
    chart: grafana
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 6.58.9
    helm:
      releaseName: grafana
      values: |
        persistence:
          enabled: true


  destination:
    server: "https://kubernetes.default.svc"
    namespace: metrics
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
