apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cnpg
  namespace: argocd
spec:
  project: core
  source:
    chart: cloudnative-pg
    repoURL: https://cloudnative-pg.github.io/charts
    targetRevision: 0.18.2
    helm:
      releaseName: cloudnative-pg
  destination:
    server: "https://kubernetes.default.svc"
    namespace: cnpg-system
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
