apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  project: core
  source:
    chart: traefik
    repoURL: https://traefik.github.io/charts
    targetRevision: 31.0.0
    helm:
      releaseName: traefik
      values: |
        image:
          registry: docker.io
          repository: traefik
          # defaults to appVersion
        deployment:
          replicas: 1
        additionalArguments:
          - "--api.insecure=true"
          - "--serversTransport.insecureSkipVerify=true"
        providers:
          kubernetesCRD:
            enabled: true
            allowCrossNamespace: true
            allowExternalNameServices: true
            allowEmptyServices: true
          kubernetesIngress:
            enabled: true
            allowExternalNameServices: true
            allowEmptyServices: true
        service:
          annotations:
            external-dns.alpha.kubernetes.io/hostname: lb.v2.socomp.se
            metallb.universe.tf/ip-allocated-from-pool: lan
          type: LoadBalancer
  destination:
    server: "https://kubernetes.default.svc"
    namespace: traefik
  syncPolicy:
    syncOptions:
      - CreateNamespace=true

