apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.init: regex:^3.10.*
    fluxcd.io/tag.podinfod: semver:~3.1
  namespace: monitoring
