apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-ludvika-deployment
  namespace: minecraft
  labels:
    app: mc3
spec:
  replicas: 0
  selector:
    matchLabels:
      app: mc3
  template:
    metadata:
      labels:
        app: mc3
    spec:
      containers:
      - name: minecraft-ludvika
        image: itzg/minecraft-server
        env:
        - name: EULA
          value: "TRUE"
        volumeMounts:
          - mountPath: /data
            name: data
      volumes:
        - name: data
          hostPath:
            # directory location on host
            path: /mnt/plex/minecraft/3
            # this field is optional
            type: Directory
      nodeSelector:
        cpu: amd64

---

kind: Service
apiVersion: v1
metadata:
  name: mc2-service-ludvika
  namespace: minecraft
spec:
  type: NodePort
  selector:
    app: mc3
  ports:
  - protocol: TCP
    nodePort: 32102
    port: 25565
    targetPort: 25565