apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-survival
  namespace: minecraft
  labels:
    app: mc-s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mc-s
  template:
    metadata:
      labels:
        app: mc-s
    spec:
      containers:
      - name: minecraft
        image: itzg/minecraft-server
        resources:
          requests:
            memory: "512Mi"
            cpu: "100m"
          limits:
            memory: "2048Mi"
            cpu: "2000m"
        env:
        - name: EULA
          value: "TRUE"
        - name: MEMORY
          value: 2G
        ports:
          - containerPort: 25565 
        volumeMounts:
          - mountPath: /data
            name: data
      volumes:
        - name: data
          hostPath:
            # directory location on host
            path: /mnt/plex/minecraft/survival
            # this field is optional
            type: Directory
      nodeSelector:
        cpu: amd64

---

kind: Service
apiVersion: v1
metadata:
  name: mc-service-survival
  namespace: minecraft
spec:
  type: NodePort
  selector:
    app: mc-s
  ports:
  - protocol: TCP
    nodePort: 32110
    port: 25565
    targetPort: 25565
