apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-jarfalla-deployment
  namespace: minecraft
  labels:
    app: mc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mc2
  template:
    metadata:
      labels:
        app: mc2
    spec:
      containers:
      - name: minecraft-jarfalla
        image: itzg/minecraft-server
        env:
        - name: EULA
          value: "TRUE"
        volumeMounts:
          - mountPath: /data
            name: data
      volumes:
        - name: data
          hostPath:
            # directory location on host
            path: /mnt/plex/minecraft/2
            # this field is optional
            type: Directory
      nodeSelector:
        cpu: amd64

---

kind: Service
apiVersion: v1
metadata:
  name: mc2-service-jarfalla
  namespace: minecraft
spec:
  type: NodePort
  selector:
    app: mc2
  ports:
  - protocol: TCP
    nodePort: 32101
    port: 25565
    targetPort: 25565