apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-survival
  labels:
    app: mc-s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mc-s
  template:
    metadata:
      labels:
        app: mc-s
    spec:
      containers:
      - name: minecraft
        image: itzg/minecraft-server
        env:
        - name: EULA
          value: "TRUE"
        ports:
          - containerPort: 8123
        volumeMounts:
          - mountPath: /data
            name: data
      volumes:
        - name: data
          hostPath:
            # directory location on host
            path: /mnt/plex/minecraft/survival
            # this field is optional
            type: Directory
      nodeSelector:
        cpu: amd64

---

kind: Service
apiVersion: v1
metadata:
  name: mc-service-survival
spec:
  type: NodePort
  selector:
    app: mc-s
  ports:
  - protocol: TCP
    nodePort: 32110
    port: 25565
    targetPort: 25565