#!/usr/bin/env bash
# Regenerate configmap-server.yaml from irc_relay.py and stamp the checksum
# onto deployment.yaml so ArgoCD actually rolls the pod on a code change.
#
# irc_relay.py is the source of truth. configmap-server.yaml is generated -
# never edit it by hand. Run this and commit both after every code change.
#
# Usage:  ./generate-configmap.sh

set -euo pipefail
HERE="$(dirname "$0")"

python3 - "$HERE/irc_relay.py" "$HERE/configmap-server.yaml" "$HERE/deployment.yaml" <<'PY'
import hashlib, pathlib, re, sys

src, out, dep = (pathlib.Path(p) for p in sys.argv[1:4])

body = "\n".join("    " + l if l.strip() else "" for l in src.read_text().split("\n"))
out.write_text(
    "# GENERATED by generate-configmap.sh from irc_relay.py - do not edit by hand.\n"
    "apiVersion: v1\n"
    "kind: ConfigMap\n"
    "metadata:\n"
    "  name: irc-relay-server\n"
    "  namespace: irc-relay\n"
    "data:\n"
    "  irc_relay.py: |\n" + body + "\n"
)
size = len(out.read_bytes())
print(f"wrote {out} from {src.name} ({size} bytes)")
if size > 900_000:
    print("WARNING: approaching the 1 MiB ConfigMap limit", file=sys.stderr)

# The relay owns a live IRC socket, so unlike a stateless server it cannot pick
# up a new ConfigMap without a restart. Stamping the hash forces one.
digest = hashlib.sha256(out.read_bytes()).hexdigest()[:16]
text = dep.read_text()
patched = re.sub(r'(checksum/relay: ").*(")', r'\g<1>' + digest + r'\g<2>', text, count=1)
if patched != text:
    dep.write_text(patched)
    print(f"stamped checksum/relay={digest} onto {dep.name}")
else:
    print(f"checksum/relay already {digest}")
PY
